# Generated by Django 3.1.1 on 2021-12-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_watch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='option',
            new_name='option1',
        ),
        migrations.AddField(
            model_name='questions',
            name='option2',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='option3',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='option4',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
