# Generated by Django 3.1.1 on 2021-12-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_watch', '0005_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='body',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
